# Generated by Django 5.2.3 on 2025-06-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SetupProdutos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField()),
                ('valor_produto', models.FloatField(blank=True)),
                ('descricao_produto', models.TextField(blank=True)),
            ],
        ),
    ]
